# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/xtal/setMaterial G4_Si
/xtal/setAngle 0. -25.25E-6 0. rad
/xtal/setSize 1.0 70. 100.94 mm
/xtal/setBR 3.416 0. 0. cm
/xtal/setEC data/Si220pl

/run/initialize
#
# Visualization setting
/control/execute vis.mac
